services:
  - type: web
    name: quantium-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: ADMIN_EMAIL
        value: admin@quantum.in
      - key: ADMIN_PASSWORD_HASH
        value: $2a$10$0A/6j/EqElG3RvwF015tVO/kgi0D/ldzb6I2bgZIFjDVElO8Jfthm
      - key: ADMIN_NAME
        value: Admin
