import { formatINR, formatDate } from "../api/client.js";

export function downloadStudentPDF(student, payments, monthlyRecords, coaching) {
  const win = window.open("", "_blank");
  if (!win) { alert("Please allow popups to download PDF"); return; }
  const institute = coaching || { name: "Quantum", tagline: "Coaching & Learning", address: "", phone: "", email: "" };
  const rows = (monthlyRecords || []).map((r) => `
    <tr>
      <td style="padding:8px;border:1px solid #E5E5E5">${r.label}</td>
      <td style="padding:8px;border:1px solid #E5E5E5">${formatDate(r.dueDate)}</td>
      <td style="padding:8px;border:1px solid #E5E5E5;text-align:right">${formatINR(r.monthlyFee)}</td>
      <td style="padding:8px;border:1px solid #E5E5E5;text-align:right">${formatINR(r.paid)}</td>
      <td style="padding:8px;border:1px solid #E5E5E5;text-align:right">${formatINR(r.remaining)}</td>
      <td style="padding:8px;border:1px solid #E5E5E5">${r.payments?.[0]?.date ? formatDate(r.payments[0].date) : "—"}</td>
      <td style="padding:8px;border:1px solid #E5E5E5">${r.payments?.[0]?.method || "—"}</td>
      <td style="padding:8px;border:1px solid #E5E5E5;font-size:10px">${r.payments?.[0]?.receiptNumber || "—"}</td>
      <td style="padding:8px;border:1px solid #E5E5E5"><span style="background:${r.status==='Paid'?'#000;color:#fff': r.status==='Partially Paid'?'#525252;color:#fff':'#F5F5F5'};padding:2px 6px;border-radius:999px;font-size:10px">${r.status}</span></td>
    </tr>
  `).join("");

  const html = `
  <html><head><title>${student.name}_Fee_Report.pdf</title>
  <style>body{font-family:Inter, sans-serif; color:#000; margin:40px} table{border-collapse:collapse;width:100%}</style>
  </head><body>
    <div style="display:flex;justify-content:space-between;border-bottom:2px solid #000;padding-bottom:12px">
      <div><div style="font-size:20px;font-weight:800;letter-spacing:0.18em">QUANTUM</div><div style="font-size:10px;letter-spacing:0.2em;color:#525252">${institute.tagline||"COACHING & LEARNING"}</div><div style="font-size:11px;color:#525252;margin-top:4px">${institute.address||""} ${institute.phone||""} ${institute.email||""}</div></div>
      <div style="text-align:right"><div style="font-size:12px;font-weight:700">Fee Report</div><div style="font-size:11px;color:#525252">${new Date().toLocaleDateString("en-IN")}</div></div>
    </div>
    <h3>Student Information</h3>
    <table><tr><td><b>Name</b> ${student.name}</td><td><b>ID</b> ${student.studentId}</td></tr>
    <tr><td><b>Phone</b> ${student.phone}</td><td><b>Email</b> ${student.email||"—"}</td></tr>
    <tr><td colspan="2"><b>Address</b> ${student.address||"—"}</td></tr>
    <tr><td><b>Course</b> ${student.course}</td><td><b>Batch</b> ${student.batch}</td></tr>
    <tr><td><b>Joining</b> ${formatDate(student.joiningDate)}</td><td><b>Status</b> ${student.status||"Active"}</td></tr></table>
    <h3>Fee Summary</h3>
    <table><tr><td>Total Course Fee: ${formatINR(student.totalFee)}</td><td>Monthly Fee: ${formatINR(student.monthlyFee)}</td></tr>
    <tr><td>Total Paid: ${formatINR(student.paid)}</td><td>Total Pending: ${formatINR(student.pending)}</td></tr>
    <tr><td colspan="2">Current Status: ${student.status||""}</td></tr></table>
    <h3>Complete Fee History</h3>
    <table><thead><tr style="background:#F5F5F5"><th>Month</th><th>Due Date</th><th>Fee</th><th>Paid</th><th>Remaining</th><th>Pay Date</th><th>Method</th><th>Receipt</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table>
    <p style="margin-top:30px;font-size:11px;color:#525252;text-align:center">Generated by Quantum Fee Management — ${new Date().toLocaleString("en-IN")}</p>
    <script>window.print()</script>
  </body></html>`;
  win.document.write(html);
  win.document.close();
  // file name hint via title
}

export function printReceipt(payment, student, coaching) {
  const win = window.open("", "_blank");
  if (!win) return;
  const html = `<html><head><title>${payment.receiptNumber}</title><style>body{font-family:Inter,sans-serif;padding:40px} .hdr{border-bottom:2px solid #000;padding-bottom:12px;display:flex;justify-content:space-between}</style></head><body>
    <div class="hdr"><div><div style="font-size:20px;font-weight:800;letter-spacing:0.18em">QUANTUM</div><div style="font-size:10px;color:#525252">COACHING & LEARNING</div></div><div style="text-align:right"><div>Fee Receipt</div><div style="font-size:12px">${payment.receiptNumber}</div></div></div>
    <p><b>Student:</b> ${student?.name||payment.studentName} (${student?.studentId||""})<br><b>Course:</b> ${student?.course||""} <b>Batch:</b> ${student?.batch||""}<br><b>Date:</b> ${formatDate(payment.date)} <b>Method:</b> ${payment.method} ${payment.transactionId||""}<br><b>Amount:</b> ${formatINR(payment.amount)} <b>For:</b> ${payment.paymentFor||""}<br><b>Remaining:</b> ${formatINR((student?.pending)||0)}</p>
    <script>window.print()</script></body></html>`;
  win.document.write(html);
  win.document.close();
}
